-- CreateTable
-- Backs checkRateLimit() in src/lib/rate-limit.ts, which upserts rows via
-- raw SQL (INSERT ... ON CONFLICT ("key")). The PRIMARY KEY on "key" is
-- what gives Postgres the unique index that ON CONFLICT ("key") requires.
