import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { prisma } from "@/lib/prisma";
import { SiteHeader } from "@/components/site-header";

type HistoryPageProps = { searchParams: Promise<{ workspaceId?: string }> };
function formatDate(date: Date) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date); }
export default async function HistoryPage({ searchParams }: HistoryPageProps) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { workspaceId } = await searchParams;
  const workspaces = await prisma.workspace.findMany({ where: { members: { some: { userId: user.id } } }, select: { id: true, name: true }, orderBy: { updatedAt: "desc" } });
  const selectedWorkspace = workspaceId ? workspaces.find((workspace) => workspace.id === workspaceId) : null;
  const messages = await prisma.chatMessage.findMany({ where: { userId: user.id, ...(selectedWorkspace ? { workspaceId: selectedWorkspace.id } : { workspace: { members: { some: { userId: user.id } } } }) }, include: { workspace: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" }, take: 100 });
  return <div className="min-h-screen bg-paper"><SiteHeader variant="app" /><main className="mx-auto w-full max-w-6xl px-4 pb-12 pt-6 sm:px-6 sm:pb-20 sm:pt-10 lg:px-8"><div className="border-b border-line pb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo">Your conversations</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-white sm:text-5xl">Workspace History</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-ink-muted">Review questions and grounded answers from your uploaded documents, then continue asking in Chat.</p></div><div className="mt-8 flex flex-wrap gap-2">{workspaces.map((workspace) => <Link key={workspace.id} href={`/search?workspaceId=${workspace.id}`} className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition ${selectedWorkspace?.id === workspace.id ? "border-indigo bg-indigo/20 text-white" : "border-line text-ink-muted hover:border-indigo hover:text-white"}`}>{workspace.name}</Link>)}</div>{messages.length === 0 ? <section className="dark-panel mt-8 rounded-2xl p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-indigo/15 text-2xl text-[#a486ff]">⌁</div><h2 className="mt-5 text-xl font-semibold text-white">No conversation history yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink-muted">Open a workspace, upload a document, and ask your first grounded question. Your conversation will appear here.</p><Link href={selectedWorkspace ? `/workspaces/${selectedWorkspace.id}` : "/workspaces"} className="gradient-button mt-5 inline-flex h-10 items-center rounded-xl px-4 text-sm font-semibold text-white">Ask in Chat <span className="ml-2">→</span></Link></section> : <section className="mt-8 space-y-4">{messages.map((message) => <article key={message.id} className={`rounded-2xl border p-5 ${message.role === "user" ? "border-highlight/25 bg-highlight/[.06]" : "border-line bg-paper-raised"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${message.role === "user" ? "bg-highlight/15 text-highlight" : "bg-indigo/15 text-[#b49dff]"}`}>{message.role === "user" ? "Question" : "Grounded answer"}</span><span className="text-xs text-ink-muted">{message.workspace.name}</span></div><time className="text-xs text-ink-muted">{formatDate(message.createdAt)}</time></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-white/90">{message.content}</p></article>)}<div className="flex justify-center pt-3"><Link href={selectedWorkspace ? `/workspaces/${selectedWorkspace.id}` : "/workspaces"} className="gradient-button inline-flex h-11 items-center rounded-xl px-5 text-sm font-bold text-white">Ask another question <span className="ml-2">↗</span></Link></div></section>}</main></div>;
}
